# Site settings
title: Andy Blog 
header-img: img/post-bg-js-module.jpg
email: 
description: "好好学习"
baseurl: ""
url: "http://andysinlight.github.io"
twitter_username: Andy
github_username:  Andy
facebook_username:  Andy
weibo_username: Andy
zhihu_username: Andy

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
